lang: "ru"

githubUrl: "https://github.com/htmlacademy/intensive-javascript-criteria"
issuesUrl: "https://github.com/htmlacademy/intensive-javascript-criteria/issues"
pullsUrl: "https://github.com/htmlacademy/intensive-javascript-criteria/pulls"

theme: minimal-mistakes-jekyll

#markdown: CommonMark